export const GET_SONGS = "GET_SONGS"
export const ADD_SONG = "ADD_SONG"
export const DELETE_SONG = "DELETE_SONG"
export const CLEAR_SONGS = "CLEAR_SONGS"

export const ERROR_SONG = "ERROR_SONG"
export const PROGRESS_SONG = "PROGRESS_SONG"
export const STATUS_SONG = "STATUS_SONG"
export const UPLOADING_SONG = "UPLOADING_SONG"
export const CANCEL_SONG = "CANCEL_SONG"
export const CLEAR_STATUS_SONG = "CLEAR_STATUS_SONG"